Add support for IntelliJ 2021.3.3
KaustubhPatange/compose-color pull request #4
Opened 2022-04-07 17:45 UTC by ovitrif

Closes #3 

I added support for IntelliJ 2021.3.3 and tested by:

1. Built the plugin locally `gradle buildPlugin`
2. Located the `.zip` artifact in `build/distributions`
3. Installed it manually in IntelliJ 2021.3.3 → `Preferences` → `Plugins` → `⚙️` → `Install plugin from disk...`.

⬆️ Same tests steps from above can be used to test the PR.

### Other Small Fixes
1. Bumped the version number to `0.0.6`
2. Fixed the formatting in the `Change Notes`.
3. Fixed some minor spelling and formatting mistakes in the `README` file.
4. Proposing to rename the plugin to `Compose Color Highlighter`
   → **Motivation**: It is listed nicer and closer to the other installed plugins for Compose in the IDE:

<img width="1168" alt="Screenshot 2022-04-07 at 19 44 02" src="https://user-images.githubusercontent.com/4588074/162264597-910a2e5d-aeb5-4b35-aad2-ec6db4fbcd91.png">

2022-04-09 14:35 UTC, KaustubhPatange requested changes

2022-04-09 14:35 UTC, KaustubhPatange commented on README.md
> +# Compose Color Highlighter
@ovitrif

2022-04-09 14:35 UTC, KaustubhPatange commented on gradle.properties
> +pluginName_ = Compose Color Highlighter
@ovitrif

2022-04-09 16:52 UTC, ovitrif commented on gradle.properties
> +pluginName_ = Compose Color Highlighter
> Why did you change the plugin name? Existing users will not be able to update this plugin if you do so.

@KaustubhPatange I explained my motivation in the PR description:

> Proposing to rename the plugin to Compose Color Highlighter
> → Motivation: It is listed nicer and closer to the other installed plugins for Compose in the IDE:

It was a **proposal** but it's perfectly fine with me if you don't agree, I can change it back 👍

2022-04-09 16:52 UTC, ovitrif commented on README.md
> +# Compose Color Highlighter
> Kindly don't change anything in the readme file as well. If possible revert it as it doesn't look good when the plugin is viewed from Jetbrain's plugin website & other portals.

@KaustubhPatange How can I test this?

2022-04-09 17:00 UTC, ovitrif commented on gradle.properties
> +pluginName_ = Compose Color Highlighter
Reverted back to the original name 🤷‍♂️

2022-04-09 17:00 UTC, ovitrif commented on README.md
> +# Compose Color Highlighter
For now I reverted the changes to the readme file 🚀

2022-04-09 17:01 UTC, ovitrif commented
@KaustubhPatange I updated the PR with your suggestions 👍

2022-04-10 04:42 UTC, KaustubhPatange approved these changes
Looks good to me!

2022-04-10 05:00 UTC, merged